#!/bin/bash

if [ ! $# -eq 2 ]; then
    echo "" >&2
    echo "Usage: $(basename $0) <source_case> <target_case>" >&2
    echo "" >&2
    exit 1
fi

source=$1
target=$2

mkdir $target
cp -r $source/{0,constant,system} $target/
