#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf 0/*
rm -rf ./{constant,system}/{FLUID,plate}
rm -rf constant/polyMesh
rm -rf system/includeDict

# ----------------------------------------------------------------- end-of-file

